#!/usr/bin/env bash

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

# Load bundles.
antigen bundles <<EOBUNDLES
	zsh-users/zsh-autosuggestions
	zsh-users/zsh-completions
	brew
	direnv
	docker 
	docker-compose 
	extract
	git
	history
	pip
	python
	sublime
	thefuck
	osx 
	colored-man-pages 
	colorize
	djui/alias-tips
	z-shell/F-Sy-H --branch=main
	CyberShadow/per-directory-history
	MichaelAquilina/zsh-autoswitch-virtualenv
EOBUNDLES

# Load custom bundles.
antigen bundle $ZSH/custom/plugins/poetry/

# Load the theme.
antigen theme romkatv/powerlevel10k

# Tell antigen that you're done.
antigen apply
